JonathanSalwan/Triton

src/contextHandler/PINContextHandler.cpp, src/includes/NullIRBuilder.h
Because Arch ships with gcc 5.1.0 and causes the following error when building the pin libs:
> ../../../source/include/pin/compiler_version_check2.H:102:2: error: #error The C++ ABI of your compiler does not match the ABI of the pin kit.
I tried to build with clang and hit a few minor errors.  I am unsure about if REG_valid() will correctly error when passed a -1 value.
original error with clang:
> src/contextHandler/PINContextHandler.cpp:37:11: error: comparison of constant -1 with expression of type 'REG' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
=> Attempting to fix warning from clang

CMakeLists.txt
This should fix #96. Another solution would be to have it just search in the `/usr/include/x86_64-linux-gnu` directory. That would require the installation of 64-bit libc dev headers (whereas now, the 32-bit ones will suffice for this specific check since they also seem to include the 64-bit headers), so I went with this option.
=> Get only one syscalls table file.

examples/inject_model_with_snapshot.py, src/analysisProcessor/analysisProcessor.cpp, src/includes/SymbolicVariable.h, src/symbolicEngine/symbolicVariable.cpp
I added
```cpp 
bool hasConcreteValue 
```
to the SymbolicVariable class because some symbolic variables hasn't concrete value and the previous commit didn't deal with this case.
=> Improve getConcreteValue

CMakeLists.txt, scripts/triton.in
This PR provides the `-ifeellucky` option to execute Triton on a `4.x` Kernel
=> Add -ifeellucky pin option

CMakeLists.txt
in 64bit env, syscall table is setted wrong value look like 32bit table.
in this case, variable syscalls_table_files contain 32bit header + 64bit header
[/usr/include/x86_64-linux-gnu/asm/unistd_32.h, /usr/include/x86_64-linux-gnu/asm/unistd_64.h]
though 64bit env, LIST(GET syscalls_table_files 0 syscalls_table_file) is set syscalls_table_file to unistd_32.h
=> Update CMakeLists.txt (fix 64bit syscall table bug)

Dockerfile
Added a simple Docker container to allow people to try out Triton on Ubuntu 14.04. This grabs sets up a basic enviornment with clang-3.6.2 and pulls Boost from Ubuntu's packages and then builds Z3, Capstone, and Triton from source. 
Pin is also pulled down to */opt/pin-2.14-71313-gcc.4.4.7-linux*
Triton's built in */opt/Triton-master/build* or */opt/Triton/build* depending upon if you use the release link or git.
This makes setting up a development environment with Triton as simple as 
```
[ peterm@ubuntu ( 7:24AM) ~/dockerfiles/triton  ]                                  
$  docker build --tag=triton . 
```
Where you can then run it by
```
[ peterm@ubuntu ( 7:32AM) ~/dockerfiles/triton  ]                                  
$  docker run -it --rm trition
root@62e5de69f584:/# python
Python …
```
=> Added a Dockerfile to generate a container with Ubuntu 14.04 with Triton

CMakeLists.txt
It's more clear to use `option` in cmake.
Now we can run cmake in the following way:
```bash
cmake -DPINTOOL=on -DKERNEL4=on  ..
```
=> Use options in the Cmake file

src/libtriton/arch/immediateOperand.cpp
Triton creates constraint
```lisp
ref!356633 = ((_ zero_extend 32) ((_ extract 31 0) (bvadd ((_ zero_extend 32) (_ bv18446744073709551568 32)) (bvadd ((_ extract 63 0) ref!356631) (bvmul (_ bv0 64) ((_ zero_extend 32) (_ bv1 32))))))) ; LEA        operation
```
with some strange constant `(_ bv18446744073709551568 32)` (18446744073709551568 = 2<sup>64</sup> - 48 > 2<sup>32</sup>).
Immediate value in Capstone has type `int64_t`, but `ImmediateOperand` takes `uint64` value. If value size is less than `QWORD_SIZE`, it may be too big. Proposed conversion creates more appropriate constant `(_ bv4294967248 32)` in
```lisp
ref!356663 = ((_ zero_extend 32) ((_ extract 31 0) (bvadd ((_ zero_extend 32) (_ bv4294967248 32)) (bvadd ((_ extract 63 0) ref!356661) (bvmul (_ bv0 64) ((_ zero_extend 32) …
```
=> Immediate operand conversion

CMakeLists.txt
The default build script call the setup.py with `python`. On some distro (like archlinux) this is python3 which thus causes troubles.
This simply calls `env python2` instead.
=> Fix build script for distro with python3 as default python

CMakeLists.txt, src/examples/cpp/ir.cpp, src/examples/cpp/shld_test.cpp, src/libtriton/arch/x86/x86Semantics.cpp, src/libtriton/includes/pythonBindings.hpp, src/libtriton/includes/x86Semantics.hpp
Also includes some fixes for mingw build.
=> add shld semantics

src/libtriton/arch/x86/x86Semantics.cpp
It is too much trouble, I use a script.
file="src/libtriton/arch/x86/x86Semantics.cpp"
sed -r -i 's/op([0-9])->evaluate\(\)\.convert_to<bool>\(\)/!OP\1/g' ${file}
sed -r -i 's/!!OP([0-9])/OP\1/g' ${file}
sed -r -i 's/\(\(!OP([0-9]) \^ !OP([0-9])\) \| !OP([0-9])\) == false/(OP\1 == OP\2) \&\& OP\3/g' ${file}
sed -r -i 's/\(\(!OP([0-9]) \^ !OP([0-9])\) \| !OP([0-9])\) == true/(OP\1 != OP\2) \|\| !OP\3/g' ${file}
sed -r -i 's/\(OP([0-9]) \& OP([0-9])\) == true/OP\1 \&\& OP\2/g' ${file}
sed -r -i 's/\(\(OP([0-9]) \& OP([0-9])\)\) == true/OP\1 \&\& OP\2/g' ${file}
sed -r -i 's/\(!OP([0-9]) \^ !OP([0-9])\)/(OP\1 != OP\2)/g' ${file}
sed -r -i 's/\(!OP([0-9]) == !OP([0-9])\)/(OP\1 == OP\2)/g' ${file}
sed -r -i 's/\(!OP([0-9]) \| !OP([0-9])\)/(!OP\1 \|\| !OP\2)/g' ${file}
sed -r -i …
=> Use is_zero function

src/tracer/pin/main.cpp
When instrumenting a PIE binary, `IMG_Entry` return the offset of the entry point thus, the instrumentation never start. Adding `IMG_LoadOffset` ensure that the final address is really the full address of the entry point. For non-PIE binaries `IMG_LoadOffset` return 0 thus not altering the final address. **I have not checked on Windows but it does not seems to change**.
_I could have enforced by adding a switch on `IMG_Type` but as far as I understand the code the section can only be executed once for the first image of the executable (as it switch the boolean to false). Thus we might never get in this line of code for shared libraries._
=> fix startAnalysisFromEntry for PIE executable

.travis.yml, src/libtriton/arch/irBuilder.cpp, src/libtriton/arch/register.cpp, src/libtriton/arch/x86/x8664Cpu.cpp, src/libtriton/arch/x86/x86Cpu.cpp, src/libtriton/ast/astGarbageCollector.cpp, src/libtriton/bindings/python/pyXFunctions.cpp, src/libtriton/engines/symbolic/symbolicEngine.cpp, src/libtriton/includes/triton/irBuilder.hpp, src/libtriton/includes/triton/register.hpp, src/libtriton/includes/triton/solverModel.hpp, src/testers/unittests/test_semantics.py, src/testers/unittests/test_simulation.py
- Add more tests
- Fix segfault on OSX
- Fix #552
- Add testing with Linux clang 3.8 on Travis
- Fix memory leaks over the CPython API
- Fix some wrong behaviors related to implicit / explicit semantics
- Remove useless code
=> Fix segfault on OSX

.appveyor.yml, CMakeLists.txt
The calls to the unittests failed when "python" was a link to "python3" and not to "python2" and thus make check failed at least on an Arch Linux.
I only tested it without the PIN integration, but I don't think this anything.
=> Remove assumptions that the system python is python2

src/libtriton/CMakeLists.txt, src/libtriton/bindings/python/objects/pyTritonContext.cpp, src/tracer/pin/main.cpp
Hi, I have fixed following three issues:
1. [Compile Issue] Compile error in ArchLinux (gcc 8.1) and Ubuntu 16.04 (gcc 5.4)
2. [Runtime Issue] Pin tracer's signals handler misses SIGBUS
3. [Runtime Issue] Triton stops execution when z3::exception occurs
I checked if compilation successes in my following Linux.
Arch Linux (Latest):
```
K_atc% uname -r
4.17.2-1-ARCH
K_atc% gcc -v  
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared …
```
=> Fixed compile error and runtime problems

src/libtriton/engines/symbolic/symbolicSimplification.cpp
Ça permet d'appliquer une règle sur toute la profondeur d'un arbre.
=> Fix #553: Implicit node visitor and simplification

src/libtriton/arch/x86/x86Semantics.cpp, src/libtriton/includes/triton/x86Semantics.hpp
Fixed some stack instructions semantics.
Didn't find where to add the following unittests:
```
def test_push_esp(self):
ctx = TritonContext()
ctx.setArchitecture(ARCH.X86)
esp = ctx.getRegisterAst(ctx.getRegister(REG.X86.ESP))
code = [
(0xdeadbeaf, "\x54"),  # push esp
(0xdeadbeb0, "\xc3"),  # ret
]
for addr, opcode in code:
insn = Instruction()
insn.setOpcode(opcode)
insn.setAddress(addr)
ctx.processing(insn)
eip = ctx.getRegisterAst(ctx.getRegister(REG.X86.EIP))
self.assertFalse(ctx.isSat(eip != esp))
def test_popal(self):
ctx = TritonContext()
ctx.setArchitecture(ARCH.X86)
esp_old = ctx.getRegisterAst(ctx.getRegister(REG.X86.ESP))
insn = Instruction()
insn.setOpcode("\x61")  # popal
ctx.processing(insn)
esp_new = ctx.getRegisterAst(ctx.getRegister(REG.X86.ESP)) …
```
=> Semantics fixes

src/libtriton/CMakeLists.txt
We currently try to access the first element of
`syscalls${bits}_table_files`, then check if it's defined to print an error
message about missing `unistd_${bits}.h or syscall.h`.
This can't work, as Cmake will complain first about acessing the first
element of an empty list:
```
CMake Error at src/libtriton/CMakeLists.txt:172 (LIST):
LIST GET given empty list
Call Stack (most recent call first):
src/libtriton/CMakeLists.txt:194 (gen_syscall)
CMake Error at src/libtriton/CMakeLists.txt:172 (LIST):
LIST GET given empty list
Call Stack (most recent call first):
src/libtriton/CMakeLists.txt:203 (gen_syscall)
```
Fix this by checking if the list is empty instead.
=> libtriton/CMakeLists.txt: don't access head of list if list is empty

src/libtriton/ast/ast.cpp, src/libtriton/includes/triton/ast.hpp
Don't see a better way to create deep copy.
Also I think constructor `AbstractNode::AbstractNode(const AbstractNode& other, AstContext& ctxt): ctxt(ctxt)` should be deleted as there's no way to use it. Can update this pull request if you agree with it
=> Makes newIstance call itself for new node's children. Closes #718

src/libtriton/arch/x86/x86Semantics.cpp, src/libtriton/includes/triton/x86Semantics.hpp, src/samples/ir_test_suite/ir.c
I have added the pslld/psllq and vpmovmskb instruction semantics which I came across in glibc. I am not sure whether my implementation is correct, so please have a look.
I have checked for the correct end result with [this script](https://gist.github.com/Toizi/36f6d0d8a3c2a6e78d43c6055ac6e757), which generates the following output
```
before
ymm1: 0xffffff00ff000000ffffffffffffff00ffffffffffffffffffffff0000000000
eax: 0x0
executing 0x10000:  (vpmovmskb eax, ymm1)
after
ymm1: 0xffffff00ff000000ffffffffffffff00ffffffffffffffffffffff0000000000
eax: 0xe8feffe0
=============================================================
before
xmm1 = 0x0102030405060708090a0b0c0d0e0f10
executing 0x10000:  (pslld xmm1, 8)
after
xmm1 = 0x02030400060708000a0b0c000e0f1000 …
```
=> added pslld/psllq and vpmovmskb semantics

src/libtriton/ast/ast.cpp
Before this patch, it was clearing a local copy of the parents vector, so it had no effect.
I don't know if it's the best patch, but now calling `removeParent` on the node results in the parents being effectively removed from the node's parents vector.
=> Fixed parent cleaning in ast::newInstance

src/libtriton/arch/aarch64/aarch64Semantics.cpp, src/libtriton/includes/triton/aarch64Semantics.hpp
Examples:
```asm
bfi  w12, w11, #24, #8
bic  w10, w10, w9
```
=> Add semantics for bfi and bic AArch64 instructions

src/libtriton/CMakeLists.txt
When linking against triton through cmake's `add_subdirectory()`, the header include paths were not automatically set when linking with `target_link_libraries(myllib PRIVATE Triton::triton)`
I have attached a small project to test this (includes readme):
[Triton_add_subdir_test.tar.gz](https://github.com/JonathanSalwan/Triton/files/3733301/Triton_add_subdir_test.tar.gz)
=> add header dependency to improve cmake add_subdirectory support

src/libtriton/ast/ast.cpp, src/libtriton/ast/astContext.cpp, src/libtriton/ast/z3/tritonToZ3Ast.cpp, src/libtriton/engines/symbolic/symbolicEngine.cpp, src/libtriton/includes/triton/ast.hpp, src/testers/unittests/test_ast_deep.py
This version of `nodesExtraction` works 10 times faster than current implementation (See N=20000 at test_ast_deep.py). Also I incorporated the usage of this function in `newInstance` that makes a deep copy of AST node.
I don't see a nice way to make added test fail with specified timeout. Seems like unittests doesn't support it. So this test probably doesn't test a lot (just works for very long time if speed degrades) so may be it should be deleted.
There's still exists the same problem when ascending AST(which is actually a DAG) traversal is happening in `AbstractNode::init` and `AbstractNode::initParents` functions. Current version will be calling the same methods several times for already processed elements and it never finishes when applying triton to real-live obfuscators. In my …
=> Increase speed of nodes nodesExtraction algorithm and apply it in newInstance

src/libtriton/ast/ast.cpp
Actually it was because I didn't have `LxorNode` in my branch and for this class initialization leads to infinite recursion
=> Remove parent initialization in LxorNode::init

src/libtriton/arch/instruction.cpp, src/libtriton/includes/triton/instruction.hpp
This PR fixes issue. Works for examples/ir.cpp. 
Destructor wasn't visible from dll.
=> Fix to issue #828.

.appveyor.yml
Hi, 
I removed the VS13/15/17 builds, updated to VS19 the python 2.7 builds and added python 3.6 builds.
Also, I bumped z3 version to 4.8.7, libboost to 1.71.0 and python 3 builds use LIEF version 0.10.1 (to run the tests).
It should produce 4 Triton builds with Visual Studio 2019:
- x86 .lib/.dll python27 .pyd
- x86 .lib/.dll python36 .pyd
- x64 .lib/.dll python27 .pyd
- x64 .lib/.dll python36 .pyd
I can restore the older VS builds if needed.
Thanks!
=> Update Appveyor VS19 and support python 3

CMakeLists.txt
Previously, when both static build and python bindings were enabled cmake could not copy `.so` file.
=> Disable Python bindings for static build

src/libtriton/includes/triton/coreUtils.hpp
This will probably only affect Windows build since AFAIK Linux builds export all the functions by default
=> Export fromUintToBuffer and fromBufferToUintfunctions

src/libtriton/includes/triton/ast.hpp
Otherwise it will produce linker errors when using ast functions on Windows
=> TRITON_EXPORT initHash

CMakeLists.txt, src/libtriton/CMakeLists.txt
This merge fixes linking and compile flags (adds `-m32`) for cross compilation. Previously linker was not getting `-m32` flag.
=> Fix linking 32-bit Triton on a 64-bit machine

src/libtriton/arch/x86/x86Semantics.cpp
Updated MUL, IMUL and MULX to avoid making extract of extension when operands and destination are of the same size. This does not break the semantic of formulas and greatly reduce sizes of ASTs.
For few cases I check that sizes of dst, src are the same before removing the extract/sx-zx, however I have not found examples were sizes were different.
=> update semantic of imul, mul, mulx to avoid extract of sz/zx

src/libtriton/engines/symbolic/pathManager.cpp, src/testers/unittests/test_path_constraint.py
Previously `ite` formulas were pushed. We can just push a corresponding condition from them. Motivating example:
```
< (and (and (and (= (_ bv1 1) (_ bv1 1)) (not (= ref!10453 (_ bv0 8)))) (not (= ref!10458 (_ bv0 8)))) (not (= (ite (= ref!11694 (_ bv0 1)) (_ bv139860530526313 64) (_ bv139860530526257 64)) (_ bv139860530526257 64))))
---
> (and (and (and (= (_ bv1 1) (_ bv1 1)) (not (= ref!10453 (_ bv0 8)))) (not (= ref!10458 (_ bv0 8)))) (= ref!11694 (_ bv0 1)))
```
=> Push simple expressions to path constraints

src/libtriton/bindings/python/objects/pyAstContext.cpp, src/libtriton/bindings/python/objects/pyAstNode.cpp, src/libtriton/bindings/python/objects/pyBitsVector.cpp, src/libtriton/bindings/python/objects/pyImmediate.cpp, src/libtriton/bindings/python/objects/pyInstruction.cpp, src/libtriton/bindings/python/objects/pyMemoryAccess.cpp, src/libtriton/bindings/python/objects/pyPathConstraint.cpp, src/libtriton/bindings/python/objects/pyRegister.cpp, src/libtriton/bindings/python/objects/pySolverModel.cpp, src/libtriton/bindings/python/objects/pySymbolicExpression.cpp, src/libtriton/bindings/python/objects/pySymbolicVariable.cpp, src/libtriton/bindings/python/objects/pyTritonContext.cpp, src/libtriton/includes/triton/py3c_compat.h
Fixed some of the warnings since it's turned out that Python 3.8 added new field - `tp_vectorcall` in the object structure. And `tp_print` is now became `tp_vectorcall_offset`:
- https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_vectorcall_offset
- https://github.com/python/cpython/blob/master/Objects/typeobject.c#L5014
- https://renenyffenegger.ch/notes/development/languages/Python/CPython/sources/Include/cpython/object_h
Sadly, some warnings remain and I have no idea where they come from (`tp_print` was removed as documentation mentions):
```
/home/Triton/src/libtriton/bindings/python/objects/pyAstContext.cpp:1777:7: warning: missing initializer for member ‘_typeobject::tp_print’ [-Wmissing-field-initializers]
1777 |       };
|       ^
[ 70%] Building CXX object …
```
=> Fix #900 - Python 3.8 compatibility

src/libtriton/arch/x86/x86Semantics.cpp
We do not need a concrete value of CX if string instruction does not have a REP prefix.
=> Fix - string instruction without REP prefix does not require CX

src/libtriton/arch/x86/x86Semantics.cpp, src/libtriton/includes/triton/x86Semantics.hpp
Added VMOVD/VMOVQ AVX instructions. Also, I noticed a strange thing -- MOVD and MOVQ are handled differently. MOVD XMM gets [zero extended](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x86Semantics.cpp#L6823) while MOVQ XMM remains [unchanged](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x86Semantics.cpp#L7323). Intel manual says:
**MOVD/Q with XMM destination:**
Moves a dword/qword integer from the source operand and stores it in the low 32/64-bits of the destination XMM register. The upper bits of the destination are zeroed. The source operand can be a 32/64-bit register or 32/64-bit memory location.
128-bit Legacy SSE version: Bits (MAX_VL-1:128) of the corresponding YMM destination register remain unchanged. Qword operation …
=> Add x86 VMOVD/VMOVQ semantics

src/libtriton/engines/solver/z3/z3Solver.cpp
Fixes the bug that caused skipping the first model.
=> Fix #932: Remove redundant solver.check() call

src/libtriton/ast/astContext.cpp, src/libtriton/includes/triton/astContext.hpp, src/testers/unittests/test_ast_simplification.py
=> Implement concat of extract AST simplifications

src/libtriton/engines/symbolic/symbolicEngine.cpp
This merge makes printed sliced expressions more readable.
Now:
```
(assert (= ref!312542 (_ bv1 1)))
(assert (not (= ref!312501 (_ bv1 1))))
```
Instead of:
```
(assert (and (= ref!312542 (_ bv1 1)) (not (= ref!312501 (_ bv1 1)))))
```
Also, this is a workaround for recursion stack overflow during ASTs printing. I will propose a real fix later this week.
=> Print sliced expressions conjuncts asserts line by line

src/libtriton/engines/symbolic/symbolicEngine.cpp
This one fixes issue with long printed formulas when AST_OPTIMIZATIONS are on.
=> Create volatile expression for extended part to avoid long formulas while printing

src/libtriton/arch/x86/x86Semantics.cpp, src/libtriton/includes/triton/x86Semantics.hpp, src/samples/ir_test_suite/ir.c, src/testers/pin/check_semantics.py
Add semantics for `vpcmpgtb`, `vpcmpgtd`, `vpcmpgtw`, `vmovaps`, `vmovups`, `vmovsd`, `vpsubb`, `vpsubd`, `vpsubq`, `vpsubw`, `vpslldq`, `vxorps`, `packuswb`, `palignr`.
Add tests for pintool in `ir_test_suite` for these instructions and previously implemented.
=> Instruction semantics

src/libtriton/bindings/python/objects/pySymbolicExpression.cpp, src/libtriton/engines/symbolic/symbolicEngine.cpp, src/testers/unittests/test_github_issues.py, src/testers/unittests/test_symbolic_expression.py
Extend symbolic expression comments with instruction string representation. This allows explicitly match SMT formulas with corresponding instructions.
=> Print instruction in symbolic expression comment

src/examples/python/small_x86-64_symbolic_emulator.py
The [sample_1](https://github.com/JonathanSalwan/Triton/tree/master/src/examples/python/samples) binary was compiled 5 years ago (based on GH history).
For the `sample_1` binary, `__libc_start_main` is placed in the `.rela.plt` section, as you can see in the output below
```
$ readelf -r sample_1_orig
Relocation section '.rela.dyn' at offset 0x3b8 contains 1 entry:
Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000600ff8  000400000006 R_X86_64_GLOB_DAT 0000000000000000 __gmon_start__ + 0
Relocation section '.rela.plt' at offset 0x3d0 contains 4 entries:
Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000601018  000100000007 R_X86_64_JUMP_SLO 0000000000000000 strlen@GLIBC_2.2.5 + 0
000000601020  000200000007 …
```
=> Example symbolic emulator must care about dynamic relocations

src/libtriton/engines/symbolic/symbolicEngine.cpp
I was playing around with triton and big binaries (~50-200MB). I was noticing huge load times trying to concretize whole segments during initialization.
By avoiding iterating on the `alignedMemoryReference` map when empty, we save roughly 50% of CPU time. Trying to concretize 50MB on init went from ~60s to 30s.
This will still happen if you try to concretize big memory section after the symbolic execution engine did some calculation, as the map won't be empty. But this fix will allow users to optimize load times by concretizing memory during initialization at least.
=> Improve performance while setting concrete memory during initialization

src/libtriton/arch/x86/x86Specifications.cpp, src/libtriton/bindings/python/objects/pyTritonContext.cpp, src/libtriton/callbacks/callbacks.cpp, src/libtriton/includes/triton/callbacks.hpp, src/testers/unittests/test_callback.py
PR created in response to https://github.com/JonathanSalwan/Triton/issues/1035
This has more changes than the patch referenced in that issue. This causes Triton to now throw an exception if you try to remove a callback and do not find the callback. If the same callback is registered multiple times, previously one call to remove would remove all the duplicates as well. With this update remove must be called the same number of times as add.
This was added because it is necessary to prevent bad dereferences on python objects passed to `removeCallback`.
=> added a fix for reference counting with python callbacks

src/libtriton/api/api.cpp, src/libtriton/engines/solver/solverEngine.cpp, src/libtriton/engines/solver/z3/z3Solver.cpp, src/libtriton/includes/triton/api.hpp, src/libtriton/includes/triton/solverEngine.hpp, src/libtriton/includes/triton/solverInterface.hpp, src/libtriton/includes/triton/z3Solver.hpp
The motivation of this PR is following. We would like to solve queries in parallel. And sometimes we need to change solving timeout for specific queries (e.g, to detect symbolic address bounds with a small timeout). Global timeout does not allow to have different timeout for parallel queries.
=> Support overriding of global solving timeout per request

src/libtriton/CMakeLists.txt
The current way of fetching the python install directory gets the wrong one on systems where `get_python_lib()` (the general directory) differs from `get_python_lib(True)` (the platform-specific directory).  For example, on 64-bit Fedora Linux systems, the former is `/usr/lib/python[version]/site-packages` while the latter is `/usr/lib64/python[version]/site-packages`.
This commit:
- removes `from __future__ import print_function`, which is only needed for python 2
- uses `sysconfig.get_path` instead of `distutils.sysconfig.get_python_lib`.  The former has been available since python 3.2; the latter has been deprecated and will be removed in some future version of python.
=> Modernize fetching the python install directory

Dockerfile
The environment variable $PYTHONPATH is empty. With an extra command during build of docker container I insert "/usr/lib/python<version>/site-packages" into that variable and 'import triton' works.
=> Fix import triton on Python3

src/libtriton/engines/solver/z3/z3Solver.cpp
This merge fixes unhandled Z3 out of memory exception.
```
terminate called after throwing an instance of 'triton::exceptions::SolverEngine'
what():  Z3Solver::getModels(): max. memory exceeded
```
=> Catch Z3 max. memory exceeded exception and make it OUTOFMEM

src/libtriton/api/api.cpp, src/libtriton/ast/bitwuzla/tritonToBitwuzlaAst.cpp, src/libtriton/bindings/python/objects/pyTritonContext.cpp, src/libtriton/engines/solver/bitwuzla/bitwuzlaSolver.cpp, src/libtriton/includes/triton/api.hpp, src/libtriton/includes/triton/bitwuzlaSolver.hpp, src/libtriton/includes/triton/tritonToBitwuzlaAst.hpp, src/testers/unittests/test_ast_conversion.py, src/testers/unittests/test_ast_eval.py
Implemented `evaluate()` method for Bitwuzla solver. Also renamed `evaluateAstViaZ3()` -> `evaluateAstViaSolver()`. Unittests from `test_ast_eval.py` now pass for both solvers.
=> Bitwuzla evaluate

src/libtriton/engines/solver/bitwuzla/bitwuzlaSolver.cpp, src/libtriton/includes/triton/bitwuzlaSolver.hpp, src/testers/unittests/test_ast_eval.py
- Throw exception when on Bitwuzla failure on `evaluate()`
- Termination callback refactoring: remove `call_cnt` (doesn't slow solving time notable), remove `delay`-logic (checking every second is enough), doesn't check oom in first 100ms of solving (no need to check memory on easy queries). Thus, termination callback become more concise and clear.
=> Bitwuzla termination callback

README.md
Python is an optional library to build Triton. For instance Ponce does not compile python into it.
You can disable python in the build commands (`-DPYTHON_BINDINGS=OFF`):
```
cmake_dependent_option(PYTHON_BINDINGS      "Enable Python bindings"                        ON BUILD_SHARED_LIBS OFF)
```
=> Update README to reflect that python is an optional library

CMakeLists.txt, src/CMakeLists.txt, src/libtriton/CMakeLists.txt
1. `TRITON_BUILDING_DLL` is not exists, it should be `BUILDING_DLL`. See https://github.com/JonathanSalwan/Triton/blob/96104b1a860dc7ddb9ab123859b2fd668e388f72/src/libtriton/includes/triton/dllexport.hpp#L12-L17
2. `BUILDING_DLL` should only be used in build process, so it must be `PRIVATE`, not `PUBLIC`.
3. The dynamic library is not installed.
4. Add options for feature `examples` and `tests`.
Related: https://github.com/microsoft/vcpkg/pull/23111
=> [cmake] Fix pre-definintion and dynamic library installation, add options for examples and tests

src/libtriton/arch/x86/x86Specifications.cpp
This PR introduce code changes to allow using Triton with the current HEAD of [capstone-engine/capstone](https://github.com/capstone-engine/capstone) (as of writing).
I have seen the previous conversion in #972 but although capstone is not finalized yet I think there is some value to be able to try Triton with the current repository.
Especially as those code changes looks fairly backward compatible to my untrained eyes (disclaimer: I am not a heavy Triton user).
There is an interesting thread at capstone-engine/capstone#1456 which give many information about some of the capstone 5 changes, which I used as inspiration for this PR.
=> Code changes to support using capstone next

src/libtriton/api/api.cpp, src/libtriton/bindings/python/objects/pyTritonContext.cpp, src/libtriton/engines/lifters/liftingToPython.cpp, src/libtriton/engines/lifters/liftingToSMT.cpp, src/libtriton/includes/triton/api.hpp, src/libtriton/includes/triton/liftingToPython.hpp, src/libtriton/includes/triton/liftingToSMT.hpp
This PR brings back #982 for new lifting engine. One is able to use boolean argument to enable instruction assembly printing for symbolic expressions.
Closes #1133
=> Support instruction assembly printing for symbolic expressions in lifting engine

.github/workflows/python.yml
This PR fixes Capstone support for Linux and macOS (issue #1145).
=> Fix Capstone support for Linux and macOS

src/libtriton/arch/arm/aarch64/aarch64Cpu.cpp, src/libtriton/arch/arm/aarch64/aarch64Semantics.cpp, src/libtriton/arch/arm/aarch64/aarch64Specifications.cpp, src/libtriton/arch/arm/arm32/arm32Cpu.cpp, src/libtriton/arch/arm/arm32/arm32Semantics.cpp, src/libtriton/arch/arm/arm32/arm32Specifications.cpp, src/libtriton/includes/triton/aarch64Specifications.hpp, src/libtriton/includes/triton/arm32Specifications.hpp
When disassembling load/store instructions memory access size is set according to the destination register size. This is wrong for some instructions like ldrb w8, [sp, #0xc] as it takes only 1 byte.
=> AARCH64: Fix instruction memory access size when it's specified by instruction (ldrb, etc)

src/libtriton/arch/arm/aarch64/aarch64Semantics.cpp
Include TBNZ, TBZ branch instructions into path predicate by pushing path constraints
=> AARCH64: add pushing path constraint in TBNZ, TBZ semantics

src/scripts/docker/Dockerfile, src/scripts/docker/build-wheel-linux.sh
Long term solution for building Bitwuzla on Python workflow.
=> Set clang for Bitwuzla build on Python workflow

src/libtriton/arch/x86/x86Semantics.cpp, src/testers/unittests/test_callback.py
Hey @JonathanSalwan o/ There is an issue with the semantics of `call`. It has an odd behavoir that depends on whether a `GET_CONCRETE_MEMORY_VALUE` callback is set. The following snippet exposes the issue:
```python
from triton import *
def test_call(add_callback):
def get_concrete_memory_value_hook(ctx, mem):
print(f'\tInside callback, mem: {mem}')
ctx = TritonContext(ARCH.X86_64)
rsp = 0xeffffd80
ctx.setConcreteMemoryValue(MemoryAccess(rsp + 0x48, 8), 0x41c8e0)
ctx.setConcreteMemoryValue(MemoryAccess(rsp + 0x50, 8), 0x41c910)
ctx.setConcreteRegisterValue(ctx.registers.rsp, 0xeffffd80)
print(f"\t[rsp + 0x48]([{rsp + 0x48:#x}]) = {ctx.getConcreteMemoryValue(MemoryAccess(rsp + 0x48, 8)):#x}")
print(f"\t[rsp + 0x50]([{rsp + 0x50:#x}]) = {ctx.getConcreteMemoryValue(MemoryAccess(rsp + 0x50, …
```
=> Fix call semantics

src/libtriton/engines/symbolic/symbolicEngine.cpp, src/libtriton/engines/symbolic/symbolicExpression.cpp, src/libtriton/includes/triton/symbolicExpression.hpp
Hey @JonathanSalwan,
This is a small proposal, and hopefully a small enough change. If you could give some feedback it would be much appreciated :)
Currently, apart the disassembly string, symbolic expressions don't have any information regarding the original instruction that was used for lifting. Having the original address embedded in the symbolic expression would be useful to do backtracking using the backward slicing functionality (through `sliceExpressions`)
For example: looking at the dead store elimination simplification, it seems there's a [small hack](https://github.com/JonathanSalwan/Triton/blob/2b655f20528065cf70e0fa95e2d01b34a8ef6a17/src/libtriton/engines/symbolic/symbolicSimplification.cpp#L263) parsing the disassembly string to retrieve the original instruction address.
If …
=> Store instruction address in symbolic expression created from instructions.

.github/workflows/python.yml, src/scripts/docker/build-wheel-linux.sh
Tested the Github actions artifact out on my machine and it installed successfully.
Most of the build time is spent on the dependencies so this shouldn't affect it by much.
=> Build wheel for Python 3.11

src/libtriton/ast/ast.cpp, src/libtriton/includes/triton/astEnums.hpp
- ast_e should all be prime (per the existing comment in ast.hpp)
- even values appear to poorly affect triton::ast::hash2n, therefore updated IntegerNode and triton::ast::rotl to (naively) ensure the hash value is odd.
Disclaimer: I am not a mathematician
Here is the existing hash2n:
https://github.com/JonathanSalwan/Triton/blob/48de90d395a626c6247f0d71abd6cac1290daf62/src/libtriton/ast/ast.cpp#L3465-L3470
Problem:
```
>>> def hash2n(h, n):
...     mask = (1 << 512)-1
...     for i in range(n):
...         h = (h*h) & mask
...     return h
...
>>> hex(hash2n(0x234567634254235abcdef347429930357493234568, 6))
'0xe5e18ae21077c93b662e1178fad20e6f28cb5ec2729268fd1fdcee1eba6a4aa98d0ba763cc453901000000000000000000000000000000000000000000000000'
>>> …
```
=> Reduce AstNode hash collisions

src/libtriton/includes/triton/aarch64.spec
These registers were [removed](https://github.com/capstone-engine/capstone/commit/d090c76703a0884076b2a1c25a4b11c77ab0f822) in capstone `next` branch.
=> Remove deprecated ARM64 Capstone registers

src/libtriton/ast/llvm/llvmToTriton.cpp
The code is taken from `popcnt_s()` in `x86Semantics.cpp`.
=> add llvm.ctpop.i intrinsics to llvmToTriton class

src/libtriton/includes/triton/pythonBindings.hpp
During fixing a Python 3.11 build failure for Triton 0.9 (which was already fixed in the meantime) I discovered it is not necessary to include `<longintrepr.h>`. So it would be advisable to remove it as it is discouraged by upstream. See https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-c-api-porting:
> The non-limited API files `cellobject.h`, `classobject.h`, `code.h`, `context.h`, `funcobject.h`, `genobject.h` and
> `longintrepr.h` have been moved to the Include/cpython directory. Moreover, the `eval.h` header file was removed.
> These files must not be included directly, as they are already included in `Python.h`:
> [Include Files](https://docs.python.org/3/c-api/intro.html#api-includes). If they have been included directly, consider
> including `Python.h instead`. (Contributed …
=> Including longintrepr.h is not necessary

src/libtriton/CMakeLists.txt
Install directories shouldn't be hardcoded. Some distributions requires installing library files into `/usr/lib64` for example. Using `GNUInstallDirs` (https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) covers such cases.
=> Use GNUInstallDirs CMake macros

src/libtriton/ast/llvm/llvmToTriton.cpp
```
terminate called after throwing an instance of 'triton::exceptions::SolverEngine'
what():  Z3Solver::getModels(): operator is applied to arguments of the wrong sort
```
Hello. I encountered a bug when trying to lift llvm ir to triton and then to z3 expression.
llvm:
```
%a = trunc i64 %rdx to i32
%b = icmp eq %a, 0
%c = zext i1 %b to i64
ret i64 %c
```
Invalid z3 expression:
```
((_ zero_extend 63) (distinct ((_ extract 31 0) rdx) (_ bv0 32)))
```
I'm not z3 expert but not using logical node in `icmp` handler fixes this error.
=> don't convert icmp to logical node; operator is applied to arguments of the wrong sort

src/libtriton/CMakeLists.txt
While working on the issue #532 I noticed that the build is not done in parallel as the default for parallel builds is off, see https://learn.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=msvc-170
This PR adds /MP to the compile options for msvc which significantly improves the build times.
Before:
`========== Rebuild started at 12:28 AM and took 01:25.727 minutes ==========`
After:
`========== Rebuild started at 12:30 AM and took 14.323 seconds ==========`
=> Enable parallel builds for msvc

.gitignore, CMakeLists.txt, src/libtriton/CMakeLists.txt
The `find_package(PythonInterp)` and `find_package(PythonLibs)` are deprecated and on my system they were returning results from two different python versions installed (interpreter from my PATH and libraries from homebrew's python). This caused me to run into this (very confusing) error: https://github.com/JonathanSalwan/Triton/issues/1145#issuecomment-1206549486
The `Python3` package fixed this behaviour and I made sure to keep the interface compatible (`PYTHON_XXX` variables work the same). The default behaviour (you just run `cmake -B build`) now also finds the python the user would expect (the one that's currently in the PATH) and things are working properly from a virtual environment. Here is a `requirements.txt` to test:
``` …
```
=> Switch to CMake's `Python3` package

.github/workflows/python.yml, .gitignore, src/scripts/docker/Dockerfile, src/scripts/docker/build-wheel-linux.sh
This PR:
- moves the building of Triton's dependencies to the Dockerfile (it improves performance in local builds and deps are only build once). 
- switch from `setup.py` to `pypa/build` to build the wheel package (`setup.py` is deprecated for this).
- Fixes filenames in the workflow script.
=> Improve python workflow

.github/workflows/codecov.yml, .github/workflows/linux.yml, .github/workflows/osx.yml, .github/workflows/python.yml, src/libtriton/engines/solver/bitwuzla/bitwuzlaSolver.cpp, src/scripts/docker/Dockerfile
This PR upgrades Bitwuzla to version 0.2.0.
The only remaining file to update is `Dockerfile` which will upgrade once `master` syncs with `dev-v1.0`.
=> Upgrade Bitwuzla to version 0.2.0

src/libtriton/ast/bitwuzla/tritonToBitwuzla.cpp
This PR fix an issue with the in the Triton to Bitwuzla translation for `VARIABLE_NODE`. If a variable node appears more that once in an expression, different term for that node will be created. That means, `bitwuzla_mk_const` will return different `BitwuzlaTerm`s for the same symbol. The fix checks whether the term was already created and returns it, otherwise creates a new one.
=> Fix Bitwuzla VARIABLE_NODE translation

src/libtriton/ast/ast.cpp
This PR fixes how `isSymbolic` is computed for ITE nodes. The following code shows the issue:
```python
from triton import *
ctx = TritonContext(ARCH.X86_64)
ast_ctx = ctx.getAstContext()
x = ctx.newSymbolicVariable(32)
ite_node = ast_ctx.ite(
ast_ctx.equal(ast_ctx.bv(1, 1), ast_ctx.bv(1, 1)),
ast_ctx.bv(0x12345678, 32),
ast_ctx.variable(x))
print(f'[+] ITE node: {ite_node}')
print(f'[+] ITE node is symbolic? {ite_node.isSymbolized()}')
```
It will output that `ite_node` is symbolic when it is not:
```
[+] ITE node: (ite (= (_ bv1 1) (_ bv1 1)) (_ bv305419896 32) SymVar_0)
[+] ITE node is symbolic? True
```
Now we check that first whether the `IfExpr` of the ITE node is symbolic. If it is, it marks the whole node as symbolic otherwise checks each children.
Note that the problem above is …
=> Fix isSymbolic computation for IteNode

.github/workflows/docker.yml, Dockerfile
Hi :wave: 
I've noticed some difficulties while building Triton from sources using the available Dockerfile. This PR aims to fix them.
1. Now, Z3 is installed only once using pip to get rid of crashes like #1136. This also decreases the time taken to build the Docker image.
2. The test suite was not executed for the Docker image, which is now.
3. Some dependencies were missing for the test suite to run successfully.
4. The Dockerfile was cloning the source code. This prevented us from testing the changes in the CI when working on a branch other than master.
Best regards,
Manuel.
=> Fix Z3 dependency inconsistency and missing dependencies in Dockerfile

src/examples/python/lifting_dot_format.py
Execution fails when python3 is not aliased to python. Changed python to python3
=> Rename python to python3

src/libtriton/bindings/python/objects/pyTritonContext.cpp
Fix PR fixes a small memory leak in the `addCallback` function. This issue was spotted than to LIEF and their new nanobind implementation of its Python bindings (ref [here](https://nanobind.readthedocs.io/en/latest/faq.html#why-am-i-getting-errors-about-leaked-functions-and-types)).
=> Fix addCallback binding

src/libtriton/arch/x86/x8664Cpu.cpp, src/libtriton/bindings/python/objects/pyTritonContext.cpp, src/libtriton/bindings/python/utils.cpp, src/libtriton/includes/triton/x86.spec, src/testers/unittests/test_concrete_value.py
This adds the missing registers used to index into the lower portions of the AVX-512 registers. Here I have only added the registers, as well as adjust the get/set concrete register value function to use the correct parent registers. It is a simple change, and adds support for instructions using these registers.
=> Add the XMM16-31 and YMM16-31 registers for x86_64

src/libtriton/arch/arm/aarch64/aarch64Semantics.cpp, src/libtriton/arch/arm/aarch64/aarch64Specifications.cpp, src/libtriton/arch/arm/armOperandProperties.cpp, src/libtriton/includes/triton/aarch64Semantics.hpp, src/libtriton/includes/triton/archEnums.hpp
add more VAS types to correctly handle different cases which part of vector register should move to GPR register
add umov semantics in aarch64
instruction reference [here](https://developer.arm.com/documentation/dui0801/l/A64-SIMD-Vector-Instructions/UMOV--vector---A64-)
=> implement Aarch64 UMOV instruction semantics

.github/workflows/linux.yml, .github/workflows/python.yml, .gitignore, CMakeLists.txt, Dockerfile, src/libtriton/arch/arm/aarch64/aarch64Semantics.cpp, src/libtriton/engines/symbolic/symbolicEngine.cpp, src/libtriton/includes/triton/aarch64Semantics.hpp, src/libtriton/includes/triton/symbolicEngine.hpp, src/testers/aarch64/unicorn_test_aarch64.py
added tests for new instructions
drop capstone 4.0.1 support
=> More Aarch64 instruction support

src/libtriton/arch/arm/aarch64/aarch64Cpu.cpp, src/libtriton/arch/x86/x8664Cpu.cpp, src/libtriton/arch/x86/x86Cpu.cpp, src/libtriton/includes/triton/x86.spec, src/libtriton/includes/triton/x8664Cpu.hpp, src/libtriton/includes/triton/x86Cpu.hpp, src/testers/unittests/test_concrete_value.py, src/testers/unittests/test_registers.py
Adds a new test and updates the getParentRegisters implementations so that all parent register are returned, and sub-registers are not.
See https://github.com/JonathanSalwan/Triton/issues/1335
=> Ensure getParentRegisters returns all the parent register.

.github/workflows/codecov.yml, .github/workflows/linux.yml, .github/workflows/python.yml, CMakeLists.txt, src/scripts/docker/Dockerfile, src/scripts/docker/build-wheel-linux.sh
This PR updates the Python CI workflow to add support for py312 and py313 for Linux. It also fixes the wheel build script for Linux.
=> Update Python workflow

CMakeModules/FindBITWUZLA.cmake
homebrew puts bitwuzla header under the cpp dir
=> Fix bitwuzla not found on macos

src/libtriton/arch/arm/aarch64/aarch64Specifications.cpp, src/testers/aarch64/unicorn_test_aarch64.py
hola o/ 
Just a tiny fix to address some variant of bics instruction, like `bics wzr, w23, w17`, which were not recognized. 
Lo;
=> Fix unsupported instruction for some bics variant

.github/workflows/osx.yml
This PR updates the OSX workflow (runner and deps). Note that tests will fail because currently they only pass with Unicorn v2.0.0. However, Unicorn v2.0.0 does not build on the macos-14 runner.
=> Update osx workflow

.github/workflows/codecov.yml, .github/workflows/linux.yml, .github/workflows/osx.yml, .github/workflows/python.yml, src/scripts/docker/build-wheel-linux.sh
This PR updates the Python versions of some of the CI, and drops support for Python 3.8 as the end of life was 2024-10-07.
=> Update Python versions

src/libtriton/ast/llvm/tritonToLLVM.cpp
When lifting a function to LLVM, the function arguments are incorrectly sorted because each one of them isn't getting dereferenced. This causes the `operator<` overload not getting called during comparison. If the address of the first pointer happens to be greater than the second one, the following will occur:
=> Fixes improper sorting of function arguments when lifting to LLVM

doc/autocomplete/function.py, doc/autocomplete/generate_autocomplete.py, src/libtriton/bindings/python/namespaces/initOpcodesNamespace.cpp, src/libtriton/bindings/python/namespaces/initStubsNamespace.cpp, src/libtriton/bindings/python/objects/pyTritonContext.cpp
There were a lot of errors in the generated type stub file due to invalid assignments from the namespace generation and type errors using the `self.org` forward approach. The stub file now uses enums to deal with the namespaces and only sets the docstring and type information in the functions.
The new code now also tries to handle overloads by merging functions since overloads with the same name are not allowed, e.g.
```python
def disassembly(self, inst):
"""Disassembles the instruction and sets up operands."""
return self.org.disassembly(inst)
def disassembly(self, block, addr=0):
"""Disassembles a basic block with a potential given base address."""
return self.org.disassembly(block, addr=0)
def disassembly(self, addr, count):
"""Disassembles a concrete memory area from `addr` and …
```
=> fix + improve python type stubs

src/libtriton/ast/llvm/tritonToLLVM.cpp, src/libtriton/includes/triton/tritonToLLVM.hpp
I ran into problem when building with newer llvm. It shows up that LLVM 17 removed the required header.
https://stackoverflow.com/questions/76989779/compiling-a-program-that-uses-passmanagerbuilder-with-llvm-17
Passed with all current tests. Not sure if this is correct.
=> Make compatible to llvm version >= 17

src/libtriton/ast/llvm/tritonToLLVM.cpp
Extended tritonToLLVM.cpp to support 128-bit integers.
- Expanded BV_NODE to handle 128-bit bit-vectors
- Added switch cases to argument type generation and BSWAP_NODE to select 128-bit integer types
=> Add 128-bit integer support in tritonToLLVM

src/libtriton/includes/triton/modesEnums.hpp
Fix for compilation issue (ie. on fedora 42 with gcc-15):
``` 
src/libtriton/includes/triton/modesEnums.hpp:51:64: error: ‘uint64_t’ was not declared in this scope
```
=> add cstdint include

README.md
Added the right command in the README.md file to install Triton using pip, since `pip install triton` installs an entirely different package.
=> Triton can be installed using pip
