JonathanSalwan/Triton

src/bindings/python/processingPyConf.cpp
src/bindings/python/tritonCallbacks.cpp
src/includes/ProcessingPyConf.h

I add the implementation of taintMemFromAddr and untaintMemeFromAddr. It should be ok

Add taintMemFromAddr and untaintMemFromAddr

---

extra/docker/Dockerfile

Adding a Dockerfile into extra/docker/

Adding Dockerfile

---

examples/inject_model_with_snapshot.py
src/analysisProcessor/analysisProcessor.cpp
src/bindings/python/objects/PySymbolicVariable.cpp
src/includes/SymbolicVariable.h
src/symbolicEngine/symbolicVariable.cpp

Add : 
* getConcreteValue python binding
* getSymVarConcreteValue() and setSymVarConcreteValue() in the SymbolicVariable class

Enhancement #143

---

examples/inject_model_with_snapshot.py
src/analysisProcessor/analysisProcessor.cpp
src/includes/SymbolicVariable.h
src/includes/Z3ast.h
src/smt2lib/z3AST.cpp
src/symbolicEngine/symbolicVariable.cpp

Notice: This enhancement is based on #158 pull request .

Enhancement #159

---

tools/code_coverage.py

Use deepcopy instead of pointer

---

src/libtriton/arch/x86/x8664Cpu.cpp
src/libtriton/arch/x86/x86Cpu.cpp

VS2013 don't support User-defined literals https://blogs.msdn.microsoft.com/vcblog/2014/08/21/c1114-features-in-visual-studio-14-ctp3/
VS2015 does support it but PIN or DynamoRio does not support VS2015

Fix Windows compatibility 

---

CMakeLists.txt

This little thing has been bothering me for a while. I don't know why I didn't send you a PR before.

Remove including python directories if not PYTHON_BINDINGS

---

CMakeLists.txt

Sorry, I copied the wrong code from the previous pull request.

Fix mistake

---

src/libtriton/arch/instruction.cpp
src/libtriton/includes/instruction.hpp

Reverts JonathanSalwan/Triton#464

Revert "add removeWrittenRegister"

---

src/libtriton/ast/z3/z3ToTritonAst.cpp

Been following the project for a while, great work! I just corrected a few spelling errors in the Exception messages in z3ToTritonAst.cpp, nothing special.

Fix a few spelling errors in z3ToTritonAst.cpp

---

src/libtriton/arch/x86/x86Semantics.cpp
src/libtriton/includes/x86Semantics.hpp
src/samples/ir_test_suite/ir.c

I'm not quite sure about the tests in ir.c. Added some lines just to see if it works.

added semantics for VMOVDQU

---

src/libtriton/arch/x86/x8664Cpu.cpp
src/libtriton/arch/x86/x86Cpu.cpp
src/libtriton/includes/triton/peImportDirectory.hpp

Process CPU.flags as bool value for efficiency and compiler warning.
Modify non-ASCII character.

CPU.flags&non-ASCII 

---

CMakeLists.txt
src/libtriton/CMakeLists.txt

Move python related code to the same place.

Move python related code to the same place

---

src/libtriton/engines/taint/taintEngine.cpp

Elaborated the explanation about the tagging policy and propagation rules. Also rewrote the whole subsections to make the article *flow* better.

Elaborated the documentation in taintEngine.cpp

---

src/libtriton/CMakeLists.txt
src/libtriton/bindings/python/objects/pyBitsVector.cpp
src/libtriton/bindings/python/objects/pyImmediate.cpp
src/libtriton/bindings/python/objects/pyMemoryAccess.cpp
src/libtriton/bindings/python/objects/pyRegister.cpp
src/libtriton/bindings/python/objects/pyTritonContext.cpp
src/libtriton/includes/triton/bitsVector.hpp
src/libtriton/includes/triton/pythonObjects.hpp
src/testers/unittests/test_bitvector.py

* Improve code base
* Add `bv.getMaxValue()` into python bindings

Improve BitsVector Python bindings

---

src/libtriton/includes/triton/dllexport.hpp

Tested with static and dynamic (`.dll`) scenarios.

Fix for Windows static libraries

---

src/libtriton/arch/x86/x8664Cpu.cpp
src/libtriton/arch/x86/x86Cpu.cpp
src/libtriton/callbacks/callbacks.cpp

Patch for the issue #602 (https://github.com/JonathanSalwan/Triton/issues/602), almost like https://github.com/JonathanSalwan/Triton/commit/efd02cd1d693e358abb59cc17a02116c96b99d93 .

Fix issue 602

---

src/libtriton/ast/ast.cpp
src/libtriton/ast/astContext.cpp
src/libtriton/includes/triton/ast.hpp
src/libtriton/includes/triton/astContext.hpp
src/libtriton/includes/triton/coreUtils.hpp
src/libtriton/includes/triton/pythonObjects.hpp

Avoid link issue with template declaration not defined.

---

src/libtriton/arch/x86/x86Semantics.cpp

This fix https://github.com/JonathanSalwan/Triton/issues/730

Use taintUnion instead of taintAssigment for xmm comparison instructions

---

src/libtriton/arch/x86/x86Semantics.cpp

changes behavior mentioned in https://github.com/JonathanSalwan/Triton/issues/783#issuecomment-491860758

cmov expression is now tainted if relevant condition flags are tainted

---

src/tracer/pin/bindings.hpp
src/tracer/pin/init.cpp
src/tracer/pin/main.cpp

We don't need fast insertion/deletion in this case!

tracer: use vectors instead of lists for blacklists

---

src/libtriton/arch/x86/x86Semantics.cpp
src/testers/unittests/test_github_issues.py

fixed xor taint propagation with same register + added unittest

---

Dockerfile

The previous one failed to build on master.

Update dependency versions in Dockerfile

---

src/libtriton/arch/x86/x86Semantics.cpp
src/libtriton/includes/triton/x86Semantics.hpp

Added few important instructions.

jcxz subset of instructions added

---

src/examples/cpp/ctest_api.cpp
src/libtriton/api/api.cpp
src/libtriton/engines/symbolic/pathManager.cpp
src/libtriton/includes/triton/api.hpp
src/libtriton/includes/triton/pathManager.hpp

Add API method which allows you to push user-crafted pathCondition to pathManager.

Add API method for pushing path condition object

---

src/libtriton/api/api.cpp
src/libtriton/bindings/python/objects/pyTritonContext.cpp
src/libtriton/engines/symbolic/symbolicEngine.cpp
src/libtriton/includes/triton/api.hpp
src/libtriton/includes/triton/symbolicEngine.hpp

Support SMT/Python Expressions dump

---

.github/workflows/docker.yml
Dockerfile

Trying to solve https://github.com/JonathanSalwan/Triton/issues/906
Also added automated publishing of the updated docker image to the Docker Hub, works through GitHub Actions.
Please note, you also need to set corresponding "secrets" in your repository settings for publishing the image on Docker Hub. Also I am not sure what name you want to use - feel free to change those before the merge.

Docker updates

---

src/libtriton/ast/astContext.cpp
src/testers/unittests/test_ast_simplification.py

Implement bvmul AST simplification A * 1 == A

---

.appveyor.yml
.travis.yml
Dockerfile

Due to the SMT fuzzing efforts many bugs were fixed since 4.8.8.

Update Z3 to 4.8.9

---

src/libtriton/ast/astContext.cpp
src/libtriton/includes/triton/astContext.hpp
src/testers/unittests/test_ast_simplification.py

Implement extract AST simplifications

---

src/libtriton/ast/representations/astPythonRepresentation.cpp

See https://github.com/JonathanSalwan/Triton/issues/984

Fix the neg operation in python AST representation

---

src/libtriton/ast/ast.cpp
src/libtriton/ast/astContext.cpp
src/libtriton/bindings/python/objects/pyAstContext.cpp
src/libtriton/engines/symbolic/pathConstraint.cpp
src/libtriton/engines/symbolic/symbolicEngine.cpp
src/libtriton/includes/triton/ast.hpp
src/libtriton/includes/triton/pathConstraint.hpp
src/testers/unittests/test_ast_utils.py

The main purpose of this PR is supporting comments for path constraints. We need to set them for custom crafted path constraints.

Utility functions

---

src/libtriton/engines/symbolic/symbolicEngine.cpp
src/libtriton/includes/triton/symbolicEngine.hpp
src/testers/unittests/test_ast_simplification.py

Append missing instruction symbolic expressions when AST_OPTIMIZATIONS are enabled

---

src/libtriton/api/api.cpp
src/libtriton/arch/architecture.cpp
src/libtriton/bindings/python/objects/pyTritonContext.cpp
src/libtriton/includes/triton/api.hpp
src/libtriton/includes/triton/architecture.hpp
src/testers/unittests/test_disass.py

Hi!
I implemented API to disassemble multiple instructions and stop on a control flow instruction. This may be useful to execute code by blocks.
xref #1006

Disassemble to control flow instruction from concrete memory

---

src/libtriton/ast/astContext.cpp
src/testers/unittests/test_ast_simplification.py

Simplify constant ite condition.

AST optimization for ite node: True ? A : B => A, False ? A : B => B

---

src/libtriton/arch/x86/x86Semantics.cpp

syscall is a valid instruction on AMD32

Fix syscall semantics on AMD32

---

src/libtriton/api/api.cpp

Update the required libpython version and cmake command for macOS in doc

Update macOS installation doc

---

src/libtriton/arch/x86/x86Semantics.cpp
src/libtriton/includes/triton/x86Semantics.hpp
src/samples/ir_test_suite/ir.c
src/testers/pin/check_semantics.py

- Add semantics for some x86 instructions
- Improve check_semantics.py to check values of destination memory operands
- Fix semantics for xadd instruction

Instruction semantics

---

src/libtriton/engines/solver/z3/z3Solver.cpp
src/libtriton/includes/triton/z3Solver.hpp

We found out that z3 check was called twice. Seems like an easy speedup :) Thanks to @apach301

Fix double z3 solver check call

---

src/libtriton/api/api.cpp
src/libtriton/engines/solver/solverEngine.cpp
src/libtriton/engines/solver/z3/z3Solver.cpp
src/libtriton/includes/triton/api.hpp
src/libtriton/includes/triton/solverEngine.hpp
src/libtriton/includes/triton/solverInterface.hpp
src/libtriton/includes/triton/z3Solver.hpp

Added measuring solving time to switch between inputs in FuzzBench depending on summary solving time.

Added measuring solving time.

---

CMakeLists.txt
src/libtriton/CMakeLists.txt
src/libtriton/ast/bitwuzla/tritonToBitwuzlaAst.cpp
src/libtriton/bindings/python/namespaces/initSolverNamespace.cpp
src/libtriton/engines/solver/bitwuzla/bitwuzlaSolver.cpp
src/libtriton/engines/solver/solverEngine.cpp
src/libtriton/includes/triton/bitwuzlaSolver.hpp
src/libtriton/includes/triton/config.hpp.in
src/libtriton/includes/triton/solverEngine.hpp
src/libtriton/includes/triton/solverEnums.hpp
src/libtriton/includes/triton/tritonToBitwuzlaAst.hpp

Here is some preliminary support of [Bitwuzla](https://github.com/bitwuzla/bitwuzla) solver.
TODO list:

Add Bitwuzla solver

---

CMakeLists.txt
src/libtriton/CMakeLists.txt

Fix win static build

---

Dockerfile

Triton fully-equipped: LLVM for lifting; z3 or bitwuzla as SMT solver

Dockerfile for Triton with LLVM, Z3, and bitwuzla

---

Dockerfile

The previous version wasn't using the latest cmake, it had to be removed from apt list

Dockerfile with cmake >= 3.20

---

.appveyor.yml

redo of https://github.com/JonathanSalwan/Triton/pull/1137

more appveyor python versions?

---

src/libtriton/bindings/python/utils.cpp
src/libtriton/includes/triton/pythonBindings.hpp

Python 3.12 does some breaking changes that break the build. Fix them.

Fix compilation issues with python 3.12

---

.github/workflows/python.yml

This PR adds support for Bitwuzla for Linux in the `python.yml` workflow.

#1145: Add support for Linux and Bitwuzla

---

.github/workflows/python.yml

This PR adds Bitwuzla support for macOS (issue #1145).

Add Bitwuzla support for macOS

---

.github/workflows/python.yml
setup.py
src/scripts/docker/build-wheel-linux.sh

This PR sets the version number for the Wheel package and adjusts related scripts and workflow (issue #1145).

Change wheel package version number

---

src/libtriton/arch/x86/x8664Cpu.cpp
src/libtriton/arch/x86/x86Cpu.cpp
src/libtriton/arch/x86/x86Semantics.cpp
src/libtriton/includes/triton/x86.spec
src/libtriton/includes/triton/x8664Cpu.hpp
src/libtriton/includes/triton/x86Cpu.hpp

Add TSC as MSR register to support concrete RDTSC values

---

.github/workflows/python.yml
CMakeLists.txt
src/libtriton/engines/solver/bitwuzla/bitwuzlaSolver.cpp
src/scripts/docker/build-wheel-linux.sh

* Tweak and fix Wheel build process for Linux.
* Fix and improve Wheel build process for macOS.
* Disable Wheel build for Windows (temporarily).

Wheel build process improvements (issue #1145)

---

.appveyor.yml
.github/workflows/codecov.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
src/libtriton/CMakeLists.txt
src/libtriton/ast/bitwuzla/tritonToBitwuzla.cpp
src/libtriton/engines/solver/bitwuzla/bitwuzlaSolver.cpp
src/libtriton/includes/triton/bitwuzlaSolver.hpp
src/libtriton/includes/triton/tritonToBitwuzla.hpp
src/scripts/docker/Dockerfile
src/scripts/docker/build-wheel-linux.sh

This PR upgrades Bitwuzla code in Triton to work with Bitwuzla v0.1.0.

Upgrade Bitwuzla to v0.1.0

---

.github/workflows/codecov.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/python.yml
Dockerfile
README.md
src/libtriton/ast/bitwuzla/tritonToBitwuzla.cpp
src/libtriton/engines/solver/bitwuzla/bitwuzlaSolver.cpp
src/scripts/docker/Dockerfile

Mostly just fixing the TermManager API changes. Tests seem to be passing, but I didn't run all of them.

Update Bitwuzla to 0.4.0

---

.github/workflows/python.yml

This PR updates some of the GitHub's actions to their latest versions, and makes the wheel packages for py312 and py313 available for download.

Fix Python workflow

---

.github/workflows/codecov.yml
.github/workflows/docker.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/vcpkg.yml

This PR updates the GitHub's actions use in the workflows.

Update CI workflows

---

.github/workflows/codecov.yml
.github/workflows/linux.yml
.github/workflows/python.yml
src/scripts/docker/Dockerfile
src/scripts/docker/build-docker-image.sh
src/scripts/docker/build-wheel-linux.sh

This PR updates the CI to Capstone to v5.0.3, Bitwuzla to v0.7.0, and the Wheel build image from manylinux_2_31 to manylinux_2_34.

Update dependencies in CI

---

README.md

People (and my self) are having issue to enable python auto completion, might be usefull to add this to the ReadMe.
Hope that helps!

Add python autcompletion tips to doc
